class ItemResep {
  final String nama;
  final String judulDetail;
  final String gambar;
  final String rate;
  final String review;
  final String durasi;
  final String serving;
  final String tingkatKesusahan;
  final String chef;
  final List<String> bahanBahan;
  final List<String> caraMembuat;

  ItemResep({
    required this.nama,
    required this.judulDetail,
    required this.gambar,
    required this.rate,
    required this.review,
    required this.durasi,
    required this.serving,
    required this.tingkatKesusahan,
    required this.chef,
    required this.bahanBahan,
    required this.caraMembuat,
  });
}

var ListItemResep = [
  ItemResep(
      nama: 'Donut Tiramisu',
      judulDetail: 'Donut Tiramisu',
      gambar: 'images/donut.jpg',
      rate: '4.5',
      review: '300',
      durasi: '90',
      serving: '3',
      tingkatKesusahan: 'Medium',
      chef: 'Chef Muflih',
      bahanBahan: [
        '500 gr terigu',
        '60 gr gula pasir',
        '5 gr fernipan',
        '2 kuning telur',
        '250 ml air es',
        '5 gr garam',
        '60 gr margarin',
        'Toping:',
        'Glaze tiramisu',
        'Minyak goreng(sekiranya saja)',
      ],
      caraMembuat: [
        'Gausah Dibuat',
        'Gausah Dibuat',
      ]),
  ItemResep(
      nama: 'Black Forest Cake',
      judulDetail: 'Black Forest Cake',
      gambar: 'images/black_forest_cake.jpg',
      rate: '4.5',
      review: '300',
      durasi: '90',
      serving: '3',
      tingkatKesusahan: 'Medium',
      chef: 'Chef Waleed',
      bahanBahan: [
        'Bakar Semua',
        'Bakar Semua',
      ],
      caraMembuat: [
        'Gausah Dibuat',
        'Gausah Dibuat',
      ]),
  ItemResep(
      nama: 'Blueberry Cake',
      judulDetail: 'Blueberry Cake Ms Lindy',
      gambar: 'images/blueberry_cake.jpg',
      rate: '4.5',
      review: '300',
      durasi: '90',
      serving: '3',
      tingkatKesusahan: 'Medium',
      chef: 'Chef John',
      bahanBahan: [
        'Bakar Semua',
        'Bakar Semua',
      ],
      caraMembuat: [
        'Gausah Dibuat',
        'Gausah Dibuat',
      ]),
  ItemResep(
      nama: 'Green Sugar Cake',
      judulDetail: 'Green Sugar Cake',
      gambar: 'images/green_sugar_cake.jpg',
      rate: '4.5',
      review: '300',
      durasi: '90',
      serving: '3',
      tingkatKesusahan: 'Medium',
      chef: 'Chef Jack',
      bahanBahan: [
        'Bakar Semua',
        'Bakar Semua',
      ],
      caraMembuat: [
        'Gausah Dibuat',
        'Gausah Dibuat',
      ]),
];
var ListItemReseps = [
  ItemResep(
      nama: 'Donut Tiramisu',
      judulDetail: 'Donut Tiramisu',
      gambar: 'images/donut.jpg',
      rate: '4.5',
      review: '300',
      durasi: '90',
      serving: '3',
      tingkatKesusahan: 'Medium',
      chef: 'Chef Selena',
      bahanBahan: [
        '500 gr terigu',
        '60 gr gula pasir',
        '5 gr fernipan',
        '2 kuning telur',
        '250 ml air es',
        '5 gr garam',
        '60 gr margarin',
        'Toping:',
        'Glaze tiramisu',
        'Minyak goreng(sekiranya saja)',
      ],
      caraMembuat: [
  'Campur semua bahan kecuali margarin sampai setengah kalis',
  'Setelah 1/2 kalis masukan margarin uleni hingga kalis. Setelah kalis diamkan selama 30 menit',
  'Setelah 30 mnt kempeskan adonan lalu bentuk sesuai selera. Diamkan kembali 30-40 menit',
  'Panaskan minyak untuk menggoreng api kecil saja. Cukup 1x balik saja biar ga meresap minyak',
  'Untuk glaze+mingak di tim seperti mencairkan coklat aja',
  'Setelah donat sudah tidak panas bisa di toping dengan glaze caranya tinggal celupin aja',
      ]),
  ItemResep(
      nama: 'Carrot Cake',
      judulDetail: 'Carrot Cake',
      gambar: 'images/carrot_cake.jpg',
      rate: '4',
      review: '260',
      durasi: '70',
      serving: '2',
      tingkatKesusahan: 'Medium',
      chef: 'Chef Peter',
      bahanBahan: [
        '4 butir telur',
        '170 gram gula',
        '200 gram wortel (parut)',
        '200 gram terigu',
        '150 gram mentega (cairkan)',
        '2 sdm susu bubuk',
        '1/2 sdt sp',
        '1/2 sdt baking powder',
        'Sedikit vanili',
      ],
      caraMembuat: [
'Mixer gula, telur dan sp selama 10 menit dengan kecepatan tinggi sampai putih berjejak',
'Masukan tepung, bp, vanili, susu bubuk dan wortel. Mixer sebentar dengan kecepatan rendah',
'Terakhir masukan cairan mentega/minyak dan aduk rata dengan spatula. Masukan ke loyang yang sudah di olesi mentega. Hentakan 3x untuk mengeluarkan angin di dalam adonan',
'Panaskan oven selama 10 menit dengan suhu 180° C (dhy : 200° C)',
'Panggang selama 40 menit, sesuaikan dengan panas oven masing². Setelah matang, angkat dan dinginkan sebentar lalu keluarkan dari loyang',
      ]),
  ItemResep(
      nama: 'Mud Cake',
      judulDetail: 'Mud Cake',
      gambar: 'images/mud_cake.jpg',
      rate: '5',
      review: '500',
      durasi: '120',
      serving: '1',
      tingkatKesusahan: 'Hard',
      chef: 'Chef Valen',
      bahanBahan: [
        '225 gram mentega',
        '200 gram DCC',
        '350 gula pasir halus',
        '300 ml buttermilk',
        '3 telur besar',
        '1 sdt vanilla essens',
        '285 gram tepung terigu',
        '60 gram coklat bubuk',
        '1,5 sdt baking soda',
        '1 sdt baking powder',
        '1/2 sdt garam',
      ],
      caraMembuat: [
      'Hangatkan buttermilk dan campurkan dengan gula pasir, aduk dulu sampai gula larut, lalu masukkan buttermilk, masukkan telur satu persatu di mixer rendah saja',
      'Masukkan bahan C, mixer dengan kecepatan rendah',
      'Tuang ke loyang, lalu kukus dengan api sedang selama 40 menit, tes tusuk',
        'Jadi dehh....',
      ]),
  ItemResep(
      nama: 'Rainbow Cake',
      judulDetail: 'Rainbow Cake',
      gambar: 'images/rainbow_cake.jpg',
      rate: '4.2',
      review: '320',
      durasi: '60',
      serving: '8',
      tingkatKesusahan: 'Easy',
      chef: 'Chef Buggy',
      bahanBahan: [
        '5 butir telur',
        '180 gr gula pasir',
        '1 sdt emulsifier',
        '185 gr tepung terigu pro sedang',
        '85 ml santan instan',
        '50 ml susu kental manis',
        '1 sdt vanilla',
        '125 ml minyak goreng',
      ],
      caraMembuat: [
      'Masukan kedalam wadah (telur,gula, vanilla & emulsifier/ sp) Mixer dengan kecepatan paling tinggi',
    '(Saya mixer kurang lebih 10 menit) Jika sudah kental berjejak',
  'Masukan tepung terigu yang sudah di ayak',
  'Mixer sebentar saja (saya pixer dengan kecepatan paling rendah selama 30 dekit) Lalu masukan susu kental manis, santan instan & minyak goreng',
  'Aduk sampai tercampur rata',
    '(Cara mengadukannya mutar ya dari atas kebawah, lakukan seperti itu sampai semua bahan tercampur rata).',
  'Sementara itu',
  'Panaskan dulu kukusan Bagi adonan menjadi 5 bagian',
  'Beri warna masing-masing Setiap adonan di kukus selama 5 menit Lakukan sampai adonannya habis Total pengukusan 35 menit ya',
  'Yang adonan terkahir saya kukus 10 menit ( Jangan lupa tutup pengukus di alasi dengan kain bersih',
  'Agar adonan tidak menetes ke kuenya',
        'Siap santap deh',
      ]),
  ItemResep(
      nama: 'Strawberry Cake',
      judulDetail: 'Strawberry Cake',
      gambar: 'images/strawberry_cake.jpg',
      rate: '4.8',
      review: '400',
      durasi: '100',
      serving: '2',
      tingkatKesusahan: 'Hard',
      chef: 'Chef Sabo',
      bahanBahan: [
        '4 butir telur',
        '100 gr Gula pasir',
        '1/2 sdt SP',
        '100 gr terigu',
        '100 gr mentega di lelehkan',
        '1 sdt esen strawberry',
      ],
      caraMembuat: [
'Siapkan bahan-bahan',
'Mixer telur, gula pasir, dan 1/2 sdt SP sampai putih berjejak lebur 15mnt. Dan panaskan oven',
'Tambahkan 100 gr terigu, 100gr mentega leleh, dan 1 sdt esen strawberry',
'Masukkan Terigu aduk dg speed rendah',
'Aduk rata dengan spatula',
'Tuang dalam loyang D.20 yg telah di beri karlo',
'Oven dg suhu 180° selama 40°.. sesuaikan dg oven masing-masing',
'Selamat mencoba',
      ]),
  ItemResep(
      nama: 'Vanilla Cake',
      judulDetail: 'Vanilla Cake',
      gambar: 'images/vanilla_cake.jpg',
      rate: '4.7',
      review: '470',
      durasi: '90',
      serving: '6',
      tingkatKesusahan: 'Medium',
      chef: 'Chef Hamdan',
      bahanBahan: [
        '4 butir telur',
        '150 gram terigu pro rendah',
        '150 gram mentega',
        '150 gram gula',
        '5 gram SP',
        '2,5 gram baking powder',
        '1 sdt vanili cair',
        '3 sdm susu bubuk',
      ],
      caraMembuat: [
'Siapkan semua bahan. Mixer telur, gula, vanili cair dan SP selama 8 menit sampai berjejak',
'Masukkan terigu, baking powder, dan susu bubuk sedikit demi sedikit sambil diaduk perlahan',
'Masukkan mentega sedikit demi sedikit dengan spatula sampai tercampur rata',
'Tuang adonan ke dalam loyang kue 20x20',
'Panggang dengan oven pada suhu 178 derajat celcius dengan api bawah selama 50 menit. (Sesuaikan dengan jenis oven masing masing)',
'Angkat kue dan dinginkan',
'Kue bolu siap disajikan',
      ]),
  ItemResep(
      nama: 'Wedding Cake',
      judulDetail: 'Wedding Cake',
      gambar: 'images/wedding_cake.jpg',
      rate: '5',
      review: '783',
      durasi: '150',
      serving: '4',
      tingkatKesusahan: 'Very Hard',
      chef: 'Chef Rin',
      bahanBahan: [
        '200 gr tepung terigu',
        '30 gr maizena',
        '200 gr gula pasir',
        '6 butir telur',
        '1 sdt bpda',
        '1/2 sdt soda kue vanili',
        '200 gr margarine yg di lelehkan',
      ],
      caraMembuat: [
        'Pertama siapkan kukusan, lalu siapkan loyang dan semir dgn margarine lalu tabur tepung tipis-tipis',
        'Siapkan wadah masukan bahan kering, terigu,bpda,maizena dan vanili',
        'aduk rata lalu kocok telur dan gula sampai berjejak,masukan bahan kering sedikit-sedikit setelah tercampur masukan margarine aduk dengan spatula,',
        'diaduk balik sampai tercampur benar terakhir maaukan ke dalam loyang dan kukus sampai matang kurang lebih 45 menit',
        'jangan lupa kukusan nya harus udah panas dulu dan tutupnya di lapisi serbet.lalu hias deh pakai butter cream sesuka hati',
        'Happy trying',
      ]),
  ItemResep(
      nama: 'Black Forest Cake',
      judulDetail: 'Black Forest Cake',
      gambar: 'images/black_forest_cake.jpg',
      rate: '4.5',
      review: '300',
      durasi: '90',
      serving: '3',
      tingkatKesusahan: 'Medium',
      chef: 'Chef Andi',
      bahanBahan: [
        '130 gr cokelat batang, cincang',
        '10 sdm margarin',
        '4 sdm gula',
        '3 sdm tepung terigu pro sedang',
        '2 butir telur',
        '1 butir kuning telur',
        '1/4 sdt garam',
        '1 sdm cokelat bubuk',
      ],
      caraMembuat: [
      'Lelehkan margarin. Setelah leleh, tuang margarin kedalam cokelat yang sudah dicincang. Aduk hingga coklat mencair',
  'Kocok telur dan gula hingga gula larut dan warna sedikit pucat. Tuang telur ke dalam cokelat cair',
      'Masukkan tepung, garam, dan cokelat bubuk. Aduk hingga merata',
  'Siapkan cetakan. Olesi cetakan dengan margarin. Taruh adonan kedalam cetakan',
  'Masukkan adonan kedalam oven yang sudah dipanaskan. Panggang selama 12-15 menit',
  'Keluarkan adonan dari oven. Lepaskan cake dari cetakan',
        'Sajikan',
      ]),
  ItemResep(
      nama: 'Blueberry Cake',
      judulDetail: 'Blueberry Cake',
      gambar: 'images/blueberry_cake.jpg',
      rate: '4.5',
      review: '300',
      durasi: '90',
      serving: '8',
      tingkatKesusahan: 'Medium',
      chef: 'Chef Noval',
      bahanBahan: [
        '4 butir telur',
        '3 sachet gula tropicana',
        '40 gr tepung maizena',
        '50 gr selai blueberry',
      ],
      caraMembuat: [
        'Kocok telur hingga rata',
        'Masukkan dan gula. Aduk rata',
        'Masukkan tepung maizena sambil diayak',
        'Tuang ke dalam loyang. Masukkan selai blueberry kemudian aduk acak dengan menggunakan tusuk gigi/tusuk sate/garpu hingga menjadi motif seperti marmer',
        'Panggang pada suhu 175°C selama 55 menit',
        'Setelah keluar dari oven, biarkan dingin. Lalu masukkan ke dalam kulkas selama minimal 2 jam agar dingin.',
        'Sajikan dalam potongan 8 bagian atau besarnya sesuaikan selera',
      ]),
  ItemResep(
      nama: 'Green Sugar Cake',
      judulDetail: 'Green Sugar Cake',
      gambar: 'images/green_sugar_cake.jpg',
      rate: '4.5',
      review: '300',
      durasi: '90',
      serving: '3',
      tingkatKesusahan: 'Medium',
      chef: 'Chef Roka',
      bahanBahan: [
        '100 gr Terigu (aslinya 140 gr)',
        '60 gr Maizena (aslinya 10 gr)',
        '140 gr Gula pasir',
        '4 butir Telur',
        '1 sdt SP',
        '1 sdt Essence Vanila',
        '150 gr Margarin cair',
        '2 tetes Pewarna hijau',
      ],
      caraMembuat: [
      'Kocok gula, telur, SP dan vanila sampai putih mengental dan berjejak',
  'Turunkan speed mixer, campur terigu, maizena dan Pewarna hijau. Kocok agar rata saja',
  'Terakhir masukkan margarin cair dan pewarna hijau. Kocok rata. Sebenarnya pewarna hijau tidak dipakai dalam resep aslinya, karena greean tea bubuk saya terlalu pucat dan cake tidak ada kehijauan, akhirnya saya tambahkan pewarna hijau, 2 tetes juga masih kurang keluar hijaunya',
  'Tuang ke dalam loyang bulat dan taburi almond slice di atasnya',
  'Panggang dalam oven suhu 150 ° C selama 30 menit atau sesuaikan oven masing-masing. Saya pakai suhu 150 karena lebih dari itu cake sering gosong dengan oven yang saya pakai',
      ]),
];

// class ItemReseps {
//   final String nama;
//   final String judulDetail;
//   final String gambar;
//   final String rate;
//   final String review;
//   final String durasi;
//   final String serving;
//   final String tingkatKesusahan;
//   final String chef;
//   final List<String> bahanBahan;
//   final List<String> caraMembuat;
//
//   ItemReseps({
//     required this.nama,
//     required this.judulDetail,
//     required this.gambar,
//     required this.rate,
//     required this.review,
//     required this.durasi,
//     required this.serving,
//     required this.tingkatKesusahan,
//     required this.chef,
//     required this.bahanBahan,
//     required this.caraMembuat,
//   });
// }